---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# vachette
A method for visualization of PMx models.

Vachette builds off previous work done in [V2ACHER](https://ascpt.onlinelibrary.wiley.com/doi/10.1002/psp4.12679), providing a method to visualize PKPD analyses which are impacted by covariate effects.

## Installation

```{r, eval = FALSE}
remotes::install_github("certara/vachette")
```

## Examples

### IV

```{r iv}
# Import Example Data
obs.data <- read.csv(system.file(package = "vachette", "examples", "iv-obs.csv"))
typ.data <- read.csv(system.file(package = "vachette", "examples", "iv-typ.csv"))

library(vachette)

vd <-
  vachette_data(
    obs.data,
    typ.data,
    covariates = c(WT = 70),
    mappings = c(OBS = "DV",
                 x = "time"),
    ref.dosenr = 1,
    model.name = "Intravenous (i.v)"
  )

vd <- vd |>
  apply_transformations()

p.vachette(vd)
  
```

### Oral Two-Cov 

```{r oral_two_cov}
obs.data <- read.csv(system.file(package = "vachette", "examples", "oral-two-cov-obs.csv"))
typ.data  <- read.csv(system.file(package = "vachette", "examples", "oral-two-cov-typ.csv"))

vd <-
  vachette_data(
    obs.data,
    typ.data,
    covariates =  c(WT = 70, AGE = 30),
    mappings = c(OBS = "DV",
                 x = "time"),
    ref.dosenr = 1,
    model.name = "oral-two-cov"
  )

vd <- vd |>
  apply_transformations(window = 23)

p.vachette(vd)

```
